### ISSUE TITLE
Error when I run this project.

### ISSUE THREAD

**Issue by raamipja** [afifaniks/FileRetriever#2]
Error when I open folders in my android device.

In android , this app not working properly.

many times it comes like this.

![Screenshot_20200723-150404_File Retriever](https://user-images.githubusercontent.com/68326181/88272178-f3596f80-ccf5-11ea-8461-d7a2ff2ce29f.jpg)

javafx project error:

    java.io.EOFException
	at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:340)
	at java.io.DataInputStream.readUTF(DataInputStream.java:589)
	at java.io.DataInputStream.readUTF(DataInputStream.java:564)
	at server.Controller.startServer(Controller.java:222)
	at server.Controller$1.run(Controller.java:134)
	at java.lang.Thread.run(Thread.java:748)
    java.lang.NullPointerException
	at server.Controller.browseFiles(Controller.java:68)
	at server.Controller.startServer(Controller.java:230)
	at server.Controller$1.run(Controller.java:134)
	at java.lang.Thread.run(Thread.java:748)

why this error comes?

**Comment by raamipja** [comment]
I have 3 drives in my pc. but , It shows 4 drives like this

![20200723_151729](https://user-images.githubusercontent.com/68326181/88274634-a2e41100-ccf9-11ea-9f9f-234fccaafe03.jpg)

There was no folder like this in my pc. But, this app  shows like this

![20200723_152745](https://user-images.githubusercontent.com/68326181/88274773-dde64480-ccf9-11ea-8442-4323b750c8ae.jpg)

There was no Recycle.Bin folder  in my pc. But, this app  shows like this

![20200723_151935](https://user-images.githubusercontent.com/68326181/88274877-125a0080-ccfa-11ea-9d06-40252134b39c.jpg)

When go to Recycle.Bin folder it comes like this https://user-images.githubusercontent.com/68326181/88272178-f3596f80-ccf5-11ea-8461-d7a2ff2ce29f.jpg .

Can you give a solution for this?

**Comment by raamipja** [comment]
It works smoothly.

It shows many files. But , that files are not in my pc.

**Comment by afifaniks** [comment]
> It works smoothly.
> 
> It shows many files. But , that files are not in my pc.

It actually shows all the files in your directory including hidden files.

**Comment by poorvajappja** [comment]
But, some times it comes like this 
 https://user-images.githubusercontent.com/68326181/88272178-f3596f80-ccf5-11ea-8461-d7a2ff2ce29f.jpg

Why???

**Comment by raamipja** [comment]
But, some times it comes like this
https://user-images.githubusercontent.com/68326181/88272178-f3596f80-ccf5-11ea-8461-d7a2ff2ce29f.jpg

Why???
